config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'spots/places#index'

  scope module: :spots do
    resources :places do
      resources :comments, only: [:create, :index, :destroy]
    end
    get '/maps', to: 'maps#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/district.rb
class District < ApplicationRecord
  has_many :places
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :category
  belongs_to :district
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    place = Place.find(params[:place_id])
    user = current_user
    comment.place = place
    comment.user = user
    comment.save!
    redirect_to place_path(place)
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/spot/places_controller.rb
module spots
  class PlacesController < ApplicationController
    def index
      @places = Place.all

      @markers = @places.geocoded.map do |place|
        {
          lat: place.latitude,
          lng: place.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { place: place })
        }
      end
    end

    def show
      @place = Place.find(params[:id])
      @comments = Comment.where(place_id: @place.id)
      @comment = Comment.new
    end

    def new
      @place = Place.new
    end

    def create
      @place = Place.new(place_params)
      if @place.save
        redirect_to place_path(@place)
      else
        render :new
      end
    end

    def edit
      @place = Place.find(params[:id])
    end

    def update
      @place = Place.find(params[:id])
      @place.update(place_params)
      redirect_to place_path(@place)
    end

    def destroy
      @place = Place.find(params[:id])
      @place.destroy
      redirect_to places_path
    end

    private

    def place_params
      params.require(:place).permit(:name, :address, :price_level, :category_id, :district_id)
    end
  end
end

app/controllers/spots/maps_controller.rb
module Spots
  class MapsController < ApplicationController
    def index
      @places = Place.all

      @markers = @places.geocoded.map do |place|
        {
          lat: place.latitude,
          lng: place.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { place: place })
        }
      end
    end
  end
end

app/controllers/spots/places_controller.rb
module Spots
  class PlacesController < ApplicationController
    def index
      # raise
      @categories = Category.all
      @districts = District.all
      if params[:category].present?
        @placesCategory = Place.where.not(category: params[:category].to_i)
      else
        @placesCategory = []
      end

      if params[:district].present?
        @placesDistrict = Place.where.not(district: params[:district].to_i)
      else
        @placesDistrict = []
      end

      if params[:budget].present?
        @placesBudget = Place.where.not(price_level: params[:budget].to_i)
      else
        @placesBudget = []
      end

      @places = Place.all - @placesCategory - @placesDistrict - @placesBudget
    end

    def show
      @place = Place.find(params[:id])
      @comments = Comment.where(place_id: @place.id)
      @comment = Comment.new
    end

    def new
      @place = Place.new
    end

    def create
      @place = Place.new(place_params)
      if @place.save
        redirect_to place_path(@place)
      else
        render :new
      end
    end

    def edit
      @place = Place.find(params[:id])
    end

    def update
      @place = Place.find(params[:id])
      @place.update(place_params)
      redirect_to place_path(@place)
    end

    def destroy
      @place = Place.find(params[:id])
      @place.destroy
      redirect_to places_path
    end

    private

    def place_params
      params.require(:place).permit(:name, :address, :price_level, :category_id, :district_id)
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThePlace2Be</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/index.html.erb
<div class="container">
  <%= link_to "Ajouter un nouveau spot", new_place_path %>
  <div class="places-block">
    <% @places.each do |place| %>
      <%= link_to place_path(place) do %>
        <div class="place-card">
          <%= place.name %>
          <%= place.address %>
          <%= place.price_level %>
          <%= place.district.name %>
          <%= place.category.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-fluid">

  <div class="navbar-place2be">
    <div class="navbar-item-block <%= "navbar-active" if action_name == "index" && controller_name == "places" %> ">
      <%= link_to "City-guide", places_path %>
    </div>
    <div class="navbar-item-block <%= "navbar-active" if action_name == "index" && controller_name == "maps" %> ">
      <%= link_to "Map", maps_path %>
    </div>
    <%= image_tag("logo-place2be.png", class: "logo-place2be") %>
    <%= link_to "Our team", "#" %>
    <%= link_to "About us", "#" %>
  </div>

</div>

app/views/spots/maps/_info_window.html.erb
<%= link_to place_path(place) do %>
  <h2><%= place.name %></h2>
<% end %>
<p><%= place.address %></p>
<p><%= place.category.name %></p>
<p>Fourchette de prix : <%= place.price_level %>/3</p>

app/views/spots/maps/index.html.erb
<!-- <div class="background-content"> -->
  <div class="map-block">
    <div id="map"
         style="width: 100%; height: 650px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
<!-- </div> -->

app/views/spots/places/_info_window.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>

app/views/spots/places/edit.html.erb
<div class="container">
  <%= link_to "Retour", place_path(@place) %>
  <%= simple_form_for(@place) do |f| %>
    <%= f.input :name %>
    <%= f.input :price_level %>
    <%= f.association :category %>
    <%= f.association :district %>
    <%= f.submit %>
  <% end %>
</div>

app/views/spots/places/index.html.erb
<div class="background-content">
  <div class="container">
    <div class="row cards-block">
      <div class="col-12 top-bar">

        <div class="filter-bar-block">
          <%= form_tag places_path, method: :get, class: "filter-bar" do %>
            <%= select_tag "category", options_from_collection_for_select(@categories, "id", "name"), prompt: "Catégorie", class: "filter-selector" %>
            <%= select_tag "district", options_from_collection_for_select(@districts, "id", "name"), prompt: "Quartier", class: "filter-selector" %>
            <%= select_tag "budget", options_for_select(1..3), prompt: "Budget", class: "filter-selector" %>

            <%= submit_tag "Search", class: "btn btn-light" %>
          <% end %>
        </div>

        <div class="new-spot-button">
          <%= link_to "Ajouter une adresse", new_place_path %>
        </div>
      </div>
      <% @places.each do |place| %>
        <div class="col-lg-6 col-12">
          <%= link_to place_path(place) do %>
            <div class="place-card">
              <div class="card-photo-block">
                <% if place.photo.attached? %>
                  <%= cl_image_tag place.photo.key, crop: :fill, class: "card-photo" %>
                <% end %>
              </div>
              <div class="card-infos">
                <div class="card-infos-top">
                  <h2><%= place.name %></h2>
                  <p class="place-address"><%= place.address %></p>
                </div>
                <div class="card-infos-bottom">
                  <p><%= place.category.name %></p>
                  <div class="price-level">
                    <% place.price_level.to_i.times do %>
                      <i class="fas fa-euro-sign"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/places/new.html.erb
<div class="container">
  <h1>Ajoutes un spot au city-guide !</h1>
  <%= simple_form_for(@place) do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :address, label: "Addresse" %>
    <%= f.input :price_level, collection: (1..3), label: "Fourchette de prix" %>
    <%= f.association :category, label: "Type d'établissement" %>
    <%= f.association :district, label: "Quartier" %>
    <%= f.submit "Ajouter" %>
  <% end %>
</div>

app/views/spots/places/show.html.erb
<div class="container">
  <div class="place-infos">
    <h1> <%= @place.name %> </h1>
    <span> <%= @place.address %> </span>
    <span> <%= @place.category.name %> </span>
    <span> <%= @place.district.name %> </span>
    <%= link_to "Retour", places_path %>
    <%= link_to "Supprimer cet établissement", place_path(@place), data: { confirm: 'Are you sure?' }, method: :delete %>
    <%= link_to "Modifier les informations", edit_place_path(@place)%>
  </div>
  <div class="comments-blocks">
    <% @comments.each do |comment| %>
      <div class="comment-card">
        <p> <%= comment.user.name %> </p>
        <p> <%= comment.description %> </p>
        <p> <%= comment.rating %>/5 </p>
      </div>
    <% end %>
    <hr>
    <%= simple_form_for([@place, @comment]) do |f| %>
      <%= f.input :description %>
      <%= f.input :rating, collection: (1..5) %>
      <%= f.submit %>
    <% end %>
  </div>
</div>